name: hmi_widgets
description: A Flutter package helps to visualize states, values, changes and other artefacts from technological processes.
version: 0.0.1
homepage: https://github.com/a-givertzman/hmi_widgets
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart:
    git:
      url: https://github.com/a-givertzman/fl_chart.git
      ref: master
  hmi_core:
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: master
  hmi_networking:
    git:
      url: https://github.com/a-givertzman/hmi_networking.git
      ref: master
  another_flushbar: ^1.12.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  mockito: ^5.3.0
  # flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
